name: Docker Build and Run (Python Hello World)

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest   # GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t python-hello-world .

      - name: Run Docker container
        run: |
          docker run --rm python-hello-world
